# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the lint rules recommended by the Flutter team.
# See https://flutter.dev/docs/development/tools/linter
#
# For a list of all available lints, see
# https://dart-lang.github.io/linter/lints/
#
# For information on configuring custom lints, see
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  # You can temporarily disable rules here, e.g.
  # rules:
  #   avoid_print: false

# You can also specify files to exclude from analysis.
# analyzer:
#   exclude:
#     - 'lib/generated/**'
